- name: Set hyperfoil_controller_host
  set_fact:
    hyperfoil_controller_host: "{{ hostvars[groups[hyperfoil_controller_group][0]]['ansible_hostname'] }}"
- name: Apply benchmark template
  template:
    src: 'benchmarks/{{ test_name }}.yaml.j2'
    dest: '/tmp/{{ test_name }}.yaml'
- name: Upload benchmark template
  uri:
    src: '/tmp/{{ test_name }}.yaml'
    method: POST
    headers:
      Content-Type: "text/vnd.yaml; charset=UTF-8"
    url: "http://{{ hyperfoil_controller_host }}:{{ hyperfoil_controller_port }}/benchmark"
    status_code: "204"
- name: Start benchmark
  uri:
    url: "http://{{ hyperfoil_controller_host }}:{{ hyperfoil_controller_port }}/benchmark/{{ test_name }}/start"
    status_code: "202"
  register: test_run
- name: Set run ID
  set_fact:
    test_runid: "{{ test_run.location | urlsplit('path') | basename }}"
- name: Log run ID
  debug:
    msg: "Benchmark URI: {{ test_run.location }} -> {{ test_runid }}"
- name: Poll benchmark completion
  uri:
    url: "{{ test_run.location }}"
    return_content: true
  register: test_status
  # Ansible 2.7 does not support include_tasks in do-until loop so we need to inline the condition
  # See https://github.com/ansible/ansible/issues/46203 for details
  until: test_status.content | from_json | json_query('terminated')
  delay: 5
  retries: 100000
